CREATE DATABASE PROJETOPROVA;
USE PROJETOPROVA;
CREATE TABLE TBL_ESTOQUE (
ID_CODIGO INT PRIMARY KEY AUTO_INCREMENT,
TX_NOME_MEDICAMENTO VARCHAR (150) NOT NULL,
DT_PRODUCAO DATE NOT NULL,
DT_VENCIMENTO DATE NOT NULL,
NR_ESTOQUE INT NOT NULL,
NR_PRECO double NOT NULL
);

Drop table TBL_ESTOQUE
select * from TBL_ESTOQUE